version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/WebContent/resources/js"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
